package com.wonders.stpt.itemDelay.model.bo;

// default package
// Generated 2014-5-26 14:33:41 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TDelayItem generated by hbm2java
 */
@Entity
@Table(name = "T_DELAY_ITEM")
public class DelayItemBo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8590058596031805771L;
	/** */
	/**
	 */
	private String id;
	/** */
	/**
	 */
	private String pname;
	/** */
	/**
	 */
	private String pincident;
	/** */
	/**
	 */
	private String cname;
	/** */
	/**
	 */
	private String cincident;
	/** */
	/**
	 */
	private String overDate;
	/** */
	/**
	 */
	private String delayDate;
	/** */
	/**
	 */
	private String delayPerson;
	/** */
	/**
	 */
	private String delayTimes;
	/** */
	/**
	 */
	private String updateTime;
	/** */
	/**
	 */
	private String removed;

	

	public DelayItemBo(String id, String pname, String pincident, String cname,
			String cincident, String overDate, String delayDate,
			String delayPerson, String delayTimes, String updateTime,
			String removed) {
		this.id = id;
		this.pname = pname;
		this.pincident = pincident;
		this.cname = cname;
		this.cincident = cincident;
		this.overDate = overDate;
		this.delayDate = delayDate;
		this.delayPerson = delayPerson;
		this.delayTimes = delayTimes;
		this.updateTime = updateTime;
		this.removed = removed;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PNAME", length = 50)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "PINCIDENT", length = 50)
	public String getPincident() {
		return this.pincident;
	}

	public void setPincident(String pincident) {
		this.pincident = pincident;
	}

	@Column(name = "CNAME", length = 50)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "CINCIDENT", length = 50)
	public String getCincident() {
		return this.cincident;
	}

	public void setCincident(String cincident) {
		this.cincident = cincident;
	}

	@Column(name = "OVER_DATE", length = 50)
	public String getOverDate() {
		return this.overDate;
	}

	public void setOverDate(String overDate) {
		this.overDate = overDate;
	}

	@Column(name = "DELAY_DATE", length = 50)
	public String getDelayDate() {
		return this.delayDate;
	}

	public void setDelayDate(String delayDate) {
		this.delayDate = delayDate;
	}

	@Column(name = "DELAY_PERSON", length = 50)
	public String getDelayPerson() {
		return this.delayPerson;
	}

	public void setDelayPerson(String delayPerson) {
		this.delayPerson = delayPerson;
	}

	@Column(name = "DELAY_TIMES", length = 50)
	public String getDelayTimes() {
		return this.delayTimes;
	}

	public void setDelayTimes(String delayTimes) {
		this.delayTimes = delayTimes;
	}

	@Column(name = "UPDATE_TIME", length = 50)
	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "REMOVED", length = 1)
	public String getRemoved() {
		return this.removed;
	}

	public void setRemoved(String removed) {
		this.removed = removed;
	}

}
