package com.wonders.stpt.bid.model.bo;

// default package
// Generated 2013-12-7 18:50:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TBidType generated by hbm2java
 */
@Entity
@Table(name = "T_BID_TYPE")
public class TBidType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4414593764860517365L;
	/** */
	/**
	 */
	private String id;
	/** */
	/**
	 */
	private String typeName;
	/** */
	/**
	 */
	private String removed;
	
	private String flag;
	public TBidType() {
	}

	public TBidType(String id) {
		this.id = id;
	}

	public TBidType(String id, String typeName, String removed) {
		this.id = id;
		this.typeName = typeName;
		this.removed = removed;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "TYPE_NAME", length = 1000)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "REMOVED", length = 1)
	public String getRemoved() {
		return this.removed;
	}

	public void setRemoved(String removed) {
		this.removed = removed;
	}

	@Column(name = "FLAG", length = 1)
	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	
}
