package com.wonders.stpt.bid.model.bo;

// default package
// Generated 2013-12-7 18:50:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TBidPlan generated by hbm2java
 */
@Entity
@Table(name = "T_BID_PLAN")
public class TBidPlan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6352661421145824362L;
	/** */
	/**
	 */
	private String id;
	/** */
	/**
	 */
	private String typeId;
	/** */
	/**
	 */
	private String catalogId;
	/** */
	/**
	 */
	private String majorId;
	/** */
	/**
	 */
	private String projectCompany;
	/** */
	/**
	 */
	private String line;
	/** */
	/**
	 */
	private String bidNum;
	/** */
	/**
	 */
	private String projectName;
	/** */
	/**
	 */
	private String bidPlanDate;
	/** */
	/**
	 */
	private String bidAmount;
	/** */
	/**
	 */
	private String bidInfoDate;
	/** */
	/**
	 */
	private String operator;
	/** */
	/**
	 */
	private String operateTime;
	/** */
	/**
	 */
	private String removed;
	
	private String operatorName;
	
	private String status;

	public TBidPlan() {
		this.removed = "0";
		this.operateTime =  new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
	}

	public TBidPlan(String id) {
		this.id = id;
	}

	public TBidPlan(String id, String typeId, String catalogId,
			String majorId, String projectCompany, String line,
			String bidNum, String projectName, String bidPlanDate,
			String bidAmount, String bidInfoDate, String operator,
			String operateTime, String removed) {
		this.id = id;
		this.typeId = typeId;
		this.catalogId = catalogId;
		this.majorId = majorId;
		this.projectCompany = projectCompany;
		this.line = line;
		this.bidNum = bidNum;
		this.projectName = projectName;
		this.bidPlanDate = bidPlanDate;
		this.bidAmount = bidAmount;
		this.bidInfoDate = bidInfoDate;
		this.operator = operator;
		this.operateTime = operateTime;
		this.removed = removed;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "TYPE_ID", unique = true, nullable = false, length = 50)
	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	@Column(name = "CATALOG_ID", unique = true, nullable = false, length = 50)
	public String getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(String catalogId) {
		this.catalogId = catalogId;
	}

	@Column(name = "MAJOR_ID", unique = true, nullable = false, length = 50)
	public String getMajorId() {
		return this.majorId;
	}

	public void setMajorId(String majorId) {
		this.majorId = majorId;
	}

	@Column(name = "PROJECT_COMPANY", length = 1000)
	public String getProjectCompany() {
		return this.projectCompany;
	}

	public void setProjectCompany(String projectCompany) {
		this.projectCompany = projectCompany;
	}

	@Column(name = "LINE", length = 200)
	public String getLine() {
		return this.line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	@Column(name = "BID_NUM", length = 50)
	public String getBidNum() {
		return this.bidNum;
	}

	public void setBidNum(String bidNum) {
		this.bidNum = bidNum;
	}

	@Column(name = "PROJECT_NAME", length = 1000)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "BID_PLAN_DATE", length = 50)
	public String getBidPlanDate() {
		return this.bidPlanDate;
	}

	public void setBidPlanDate(String bidPlanDate) {
		this.bidPlanDate = bidPlanDate;
	}

	@Column(name = "BID_AMOUNT", length = 50)
	public String getBidAmount() {
		return this.bidAmount;
	}

	public void setBidAmount(String bidAmount) {
		this.bidAmount = bidAmount;
	}

	@Column(name = "BID_INFO_DATE", length = 50)
	public String getBidInfoDate() {
		return this.bidInfoDate;
	}

	public void setBidInfoDate(String bidInfoDate) {
		this.bidInfoDate = bidInfoDate;
	}

	@Column(name = "OPERATOR", length = 50)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATE_TIME", length = 50)
	public String getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(String operateTime) {
		this.operateTime = operateTime;
	}

	@Column(name = "REMOVED", length = 1)
	public String getRemoved() {
		return this.removed;
	}

	public void setRemoved(String removed) {
		this.removed = removed;
	}

	@Column(name = "OPERATOR_NAME", length = 50)
	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
}
