package com.wonders.stpt.dataExchange.contractWebServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ContractConnectorService service = new ContractConnectorService();
 * ContractConnectorDelegate portType = service.getContractConnectorPort();
 * portType.saveContract(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ContractConnectorService", targetNamespace = "http://contract.webservice.wonders.com/", wsdlLocation = "http://10.1.48.16:7001/investCost/ContractConnectorPort?wsdl")
public class ContractConnectorService extends Service {

	private final static URL CONTRACTCONNECTORSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.wonders.stpt.dataExchange.contractWebServiceClient.ContractConnectorService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.wonders.stpt.dataExchange.contractWebServiceClient.ContractConnectorService.class.getResource(".");
			url = new URL(baseUrl,
					"http://10.1.48.16:7001/investCost/ContractConnectorPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.1.48.16:7001/investCost/ContractConnectorPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CONTRACTCONNECTORSERVICE_WSDL_LOCATION = url;
	}

	public ContractConnectorService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ContractConnectorService() {
		super(CONTRACTCONNECTORSERVICE_WSDL_LOCATION, new QName(
				"http://contract.webservice.wonders.com/",
				"ContractConnectorService"));
	}

	/**
	 * 
	 * @return returns ContractConnectorDelegate
	 */
	@WebEndpoint(name = "ContractConnectorPort")
	public ContractConnectorDelegate getContractConnectorPort() {
		return super.getPort(new QName(
				"http://contract.webservice.wonders.com/",
				"ContractConnectorPort"), ContractConnectorDelegate.class);
	}

}
