package com.wonders.stpt.innerWork.model.bo;

// default package
// Generated 2013-12-7 18:50:17 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TBidPlan generated by hbm2java
 */
@Entity
@Table(name = "T_INNER_WORK")
public class TInnerWork implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6352661421145824352L;
	/** */
	/**
	 */
	private String id;
	/** */
	/**
	 */
	private String jobName;
	/** */
	/**
	 */
	private String process;
	/** */
	/**
	 */
	private String pfTime;
	/** */
	/**
	 */
	private String fFlag;
	/** */
	/**
	 */
	private String status;
	/** */
	/**
	 */
	private String rPeople;
	
	/**
	 * 添加：
	 * 内部工作创建时，短信所需字段
	 * 责任人loginName
	 */
	private String rPeopleLoginName;
	
	/**
	 * 添加：
	 * 内部工作创建时，短信所需字段
	 * 分管领导loginName
	 */
	private String rLeaderLoginName;
	/** */
	/**
	 */
	private String rLeader;
	/** */
	/**
	 */
	private String tick;
	/** */
	/**
	 */
	private String operator;
	/** */
	/**
	 */
	private String operateTime;
	/** */
	/**
	 */
	private String removed;
	
	private String operatorName;
	
	private String attach;

	private String bTime;
	
	private String pFlag;
	
	private String jobDemand;
	
	private String delayType;
	
	private String delayDetail;
	
	public TInnerWork() {
		this.removed = "0";
		this.operateTime =  new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
	}

	public TInnerWork(String id) {
		this.id = id;
	}

	
	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "JOB_NAME", length = 1000)
	public String getJobName() {
		return jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Column(name = "PROCESS", length = 1000)
	public String getProcess() {
		return process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "PF_TIME", length = 50)
	public String getPfTime() {
		return pfTime;
	}

	public void setPfTime(String pfTime) {
		this.pfTime = pfTime;
	}

	@Column(name = "F_FLAG", length = 1000)
	public String getfFlag() {
		return fFlag;
	}

	public void setfFlag(String fFlag) {
		this.fFlag = fFlag;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "R_PEOPLE", length = 200)
	public String getrPeople() {
		return rPeople;
	}

	public void setrPeople(String rPeople) {
		this.rPeople = rPeople;
	}
	
	@Column(name = "R_PEOPLE_LOGINNAME", length = 500)
	public String getrPeopleLoginName() {
		return rPeopleLoginName;
	}
	
	public void setrPeopleLoginName(String rPeopleLoginName) {
		this.rPeopleLoginName = rPeopleLoginName;
	}
	
	@Column(name = "R_LEADER_LOGINNAME", length = 200)
	public String getrLeaderLoginName() {
		return rLeaderLoginName;
	}
	
	public void setrLeaderLoginName(String rLeaderLoginName) {
		this.rLeaderLoginName = rLeaderLoginName;
	}

	@Column(name = "R_LEADER", length = 200)
	public String getrLeader() {
		return rLeader;
	}

	public void setrLeader(String rLeader) {
		this.rLeader = rLeader;
	}

	@Column(name = "TICK", length = 50)
	public String getTick() {
		return tick;
	}

	public void setTick(String tick) {
		this.tick = tick;
	}

	@Column(name = "OPERATOR", length = 50)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPERATE_TIME", length = 50)
	public String getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(String operateTime) {
		this.operateTime = operateTime;
	}

	@Column(name = "REMOVED", length = 1)
	public String getRemoved() {
		return this.removed;
	}

	public void setRemoved(String removed) {
		this.removed = removed;
	}

	@Column(name = "OPERATOR_NAME", length = 50)
	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "ATTACH", length = 50)
	public String getAttach() {
		return attach;
	}

	public void setAttach(String attach) {
		this.attach = attach;
	}

	@Column(name = "B_TIME", length = 50)
	public String getbTime() {
		return bTime;
	}

	public void setbTime(String bTime) {
		this.bTime = bTime;
	}

	@Column(name = "P_FLAG", length = 200)
	public String getpFlag() {
		return pFlag;
	}

	public void setpFlag(String pFlag) {
		this.pFlag = pFlag;
	}

	@Lob
    @Basic(fetch=FetchType.EAGER)
    @Column(name = "JOB_DEMAND",columnDefinition = "CLOB")
	public String getJobDemand() {
		return jobDemand;
	}

	public void setJobDemand(String jobDemand) {
		this.jobDemand = jobDemand;
	}

	@Column(name = "DELAY_TYPE", length = 1000)
	public String getDelayType() {
		return delayType;
	}

	public void setDelayType(String delayType) {
		this.delayType = delayType;
	}

	@Column(name = "DELAY_DETAIL", length = 1000)
	public String getDelayDetail() {
		return delayDetail;
	}

	public void setDelayDetail(String delayDetail) {
		this.delayDetail = delayDetail;
	}

	/**
	 * 仅作测试用，用完删除
	 */
	@Override
	public String toString() {
		return "TInnerWork [id=" + id + ", jobName=" + jobName + ", process="
				+ process + ", pfTime=" + pfTime + ", fFlag=" + fFlag
				+ ", status=" + status + ", rPeople=" + rPeople
				+ ", rPeopleLoginName=" + rPeopleLoginName + ", rLeader="
				+ rLeader + ", tick=" + tick + ", operator=" + operator
				+ ", operateTime=" + operateTime + ", removed=" + removed
				+ ", operatorName=" + operatorName + ", attach=" + attach
				+ ", bTime=" + bTime + ", pFlag=" + pFlag + ", jobDemand="
				+ jobDemand + ", delayType=" + delayType + ", delayDetail="
				+ delayDetail + "]";
	}
	
	

	
}
