package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:24:44 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataProjectCompany generated by hbm2java
 */
@Entity
@Table(name = "GREATA_PROJECT_COMPANY")
@XmlRootElement(name="ProjectCorp")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataProjectCompany implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 * 主键.
	 */
	private String id;
	/** */
	/**
	 * 协同平台项目ID.
	 */
	@XmlElement(name="PlatformID")
	private String oaId;
	/** */
	/**
	 * 项目公司代码.
	 */
	@XmlElement(name="ProjectCorpCode")
	private String projectCompanyCode;
	/** */
	/**
	 * 项目公司名称.
	 */
	@XmlElement(name="ProjectCorpName")
	private String projectCompanyName;
	/** */
	/**
	 */
	private Integer removed = 0;
	/** */
	/**
	 * 项目公司ID.
	 */
	@XmlElement(name="ProjectCorpID")
	private String projectCompanyId;
	/** */
	/**
	 * 创建时间.
	 */
	private String createTime = df.format(new Date());

	public GreataProjectCompany() {
	}

	public GreataProjectCompany(String id, String projectCompanyId) {
		this.id = id;
		this.projectCompanyId = projectCompanyId;
	}

	public GreataProjectCompany(String id, String oaId,
			String projectCompanyCode, String projectCompanyName,
			Integer removed, String projectCompanyId, String createTime) {
		this.id = id;
		this.oaId = oaId;
		this.projectCompanyCode = projectCompanyCode;
		this.projectCompanyName = projectCompanyName;
		this.removed = removed;
		this.projectCompanyId = projectCompanyId;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "OA_ID", length = 50)
	public String getOaId() {
		return this.oaId;
	}

	public void setOaId(String oaId) {
		this.oaId = oaId;
	}

	@Column(name = "PROJECT_COMPANY_CODE", length = 200)
	public String getProjectCompanyCode() {
		return this.projectCompanyCode;
	}

	public void setProjectCompanyCode(String projectCompanyCode) {
		this.projectCompanyCode = projectCompanyCode;
	}

	@Column(name = "PROJECT_COMPANY_NAME", length = 200)
	public String getProjectCompanyName() {
		return this.projectCompanyName;
	}

	public void setProjectCompanyName(String projectCompanyName) {
		this.projectCompanyName = projectCompanyName;
	}

	@Column(name = "REMOVED", precision = 5, scale = 0)
	public Integer getRemoved() {
		return this.removed;
	}

	public void setRemoved(Integer removed) {
		this.removed = removed;
	}

	@Column(name = "PROJECT_COMPANY_ID", nullable = false, length = 50)
	public String getProjectCompanyId() {
		return this.projectCompanyId;
	}

	public void setProjectCompanyId(String projectCompanyId) {
		this.projectCompanyId = projectCompanyId;
	}

	@Column(name = "CREATE_TIME", length = 100)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
