package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:55:00 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataAssetCompose generated by hbm2java
 */
@Entity
@Table(name = "GREATA_ASSET_COMPOSE")
@XmlRootElement(name="MElement")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataAssetCompose implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 */
	private String id;
	/** */
	/**
	 * 资金主键id.
	 */
	@XmlElement(name="MAmountID")
	private String amountId;
	/** */
	/**
	 * 主键id.
	 */
	@XmlElement(name="MElementID")
	private String elementId;
	/** */
	/**
	 * 组成编码.
	 */
	@XmlElement(name="MElementCode")
	private String elementCode;
	/** */
	/**
	 * 组成名称.
	 */
	@XmlElement(name="MElementName")
	private String elementName;
	/** */
	/**
	 * 级别.
	 */
	@XmlElement(name="Level")
	private String levels;
	/** */
	/**
	 */
	private String createTime = df.format(new Date());

	public GreataAssetCompose() {
	}

	public GreataAssetCompose(String id) {
		this.id = id;
	}

	public GreataAssetCompose(String id, String amountId, String elementId,
			String elementCode, String elementName, String levels,
			String createTime) {
		this.id = id;
		this.amountId = amountId;
		this.elementId = elementId;
		this.elementCode = elementCode;
		this.elementName = elementName;
		this.levels = levels;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "AMOUNT_ID", length = 50)
	public String getAmountId() {
		return this.amountId;
	}

	public void setAmountId(String amountId) {
		this.amountId = amountId;
	}

	@Column(name = "ELEMENT_ID", length = 50)
	public String getElementId() {
		return this.elementId;
	}

	public void setElementId(String elementId) {
		this.elementId = elementId;
	}

	@Column(name = "ELEMENT_CODE", length = 200)
	public String getElementCode() {
		return this.elementCode;
	}

	public void setElementCode(String elementCode) {
		this.elementCode = elementCode;
	}

	@Column(name = "ELEMENT_NAME", length = 200)
	public String getElementName() {
		return this.elementName;
	}

	public void setElementName(String elementName) {
		this.elementName = elementName;
	}

	@Column(name = "LEVELS", length = 50)
	public String getLevels() {
		return this.levels;
	}

	public void setLevels(String levels) {
		this.levels = levels;
	}

	@Column(name = "CREATE_TIME", length = 50)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
