package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:24:44 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataConstructionUnit generated by hbm2java
 */
@Entity
@Table(name = "GREATA_CONSTRUCTION_UNIT")
@XmlRootElement(name="Contractor")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataConstructionUnit implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 * 主键.
	 */
	private String id;
	/** */
	/**
	 * 单位代码.
	 */
	@XmlElement(name="GroupUnitCode")
	private String unitCode;
	/** */
	/**
	 * 单位名称.
	 */
	@XmlElement(name="GroupUnitName")
	private String unitName;
	/** */
	/**
	 * 所属集团.
	 */
	@XmlElement(name="Group")
	private String unitGroup;
	/** */
	/**
	 * 删除位.
	 */
	private Integer removed = 0;
	/** */
	/**
	 * 所属计划ID.
	 */
	@XmlElement(name="Plan")
	private String planId;
	/** */
	/**
	 * 序号.
	 */
	@XmlElement(name="GroupUnitID")
	private String unitId;
	/** */
	/**
	 * 创建时间.
	 */
	private String createTime = df.format(new Date());

	public GreataConstructionUnit() {
	}

	public GreataConstructionUnit(String id, String unitId) {
		this.id = id;
		this.unitId = unitId;
	}

	public GreataConstructionUnit(String id, String unitCode, String unitName,
			String unitGroup, Integer removed, String planId, String unitId,
			String createTime) {
		this.id = id;
		this.unitCode = unitCode;
		this.unitName = unitName;
		this.unitGroup = unitGroup;
		this.removed = removed;
		this.planId = planId;
		this.unitId = unitId;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "UNIT_CODE", length = 200)
	public String getUnitCode() {
		return this.unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	@Column(name = "UNIT_NAME", length = 200)
	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	@Column(name = "UNIT_GROUP", length = 200)
	public String getUnitGroup() {
		return this.unitGroup;
	}

	public void setUnitGroup(String unitGroup) {
		this.unitGroup = unitGroup;
	}

	@Column(name = "REMOVED", precision = 5, scale = 0)
	public Integer getRemoved() {
		return this.removed;
	}

	public void setRemoved(Integer removed) {
		this.removed = removed;
	}

	@Column(name = "PLAN_ID", length = 50)
	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	@Column(name = "UNIT_ID", nullable = false, length = 50)
	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	@Column(name = "CREATE_TIME", length = 100)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
