package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:24:44 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataEstimates generated by hbm2java
 */
@Entity
@Table(name = "GREATA_ESTIMATES")
@XmlRootElement(name="Estimate")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataEstimates implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 */
	private String id;
	/** */
	/**
	 * 项目id.
	 */
	@XmlElement(name="ProjectID")
	private String projectId;
	/** */
	/**
	 * 概算主键id.
	 */
	@XmlElement(name="EstimatesID")
	private String estimatesId;
	/** */
	/**
	 * 概算名称.
	 */
	@XmlElement(name="EstimatesName")
	private String estimatesName;
	/** */
	/**
	 * 概算类别编码.
	 */
	@XmlElement(name="EstimatesTypeCode")
	private String estimatesTypeCode;
	/** */
	/**
	 * 概算类别名称.
	 */
	@XmlElement(name="EstimatesTypeName")
	private String estimatesTypeName;
	/** */
	/**
	 * 概算基准金额.
	 */
	@XmlElement(name="FinalBaseMAmount")
	private String finalBaseAmount;
	/** */
	/**
	 * 原基准金额.
	 */
	@XmlElement(name="OriginalBaseMAmount")
	private String originalBaseAmount;
	/** */
	/**
	 * 已批准的变更总额.
	 */
	@XmlElement(name="ApprovedChangeMAmount")
	private String approvedChangeAmount;
	/** */
	/**
	 * 待审批的变更总额.
	 */
	@XmlElement(name="ToDoChangeMAmount")
	private String todoChangeAmount;
	/** */
	/**
	 * 上级概算id.
	 */
	@XmlElement(name="SuperEstimatesID")
	private String superEstimatesId;
	/** */
	/**
	 * 层级.
	 */
	@XmlElement(name="Level")
	private String levels;
	/** */
	/**
	 */
	private String createTime = df.format(new Date());

	public GreataEstimates() {
	}

	public GreataEstimates(String id) {
		this.id = id;
	}

	public GreataEstimates(String id, String projectId, String estimatesId,
			String estimatesName, String estimatesTypeCode,
			String estimatesTypeName, String finalBaseAmount,
			String originalBaseAmount, String approvedChangeAmount,
			String todoChangeAmount, String superEstimatesId, String levels,
			String createTime) {
		this.id = id;
		this.projectId = projectId;
		this.estimatesId = estimatesId;
		this.estimatesName = estimatesName;
		this.estimatesTypeCode = estimatesTypeCode;
		this.estimatesTypeName = estimatesTypeName;
		this.finalBaseAmount = finalBaseAmount;
		this.originalBaseAmount = originalBaseAmount;
		this.approvedChangeAmount = approvedChangeAmount;
		this.todoChangeAmount = todoChangeAmount;
		this.superEstimatesId = superEstimatesId;
		this.levels = levels;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PROJECT_ID", length = 50)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "ESTIMATES_ID", length = 50)
	public String getEstimatesId() {
		return this.estimatesId;
	}

	public void setEstimatesId(String estimatesId) {
		this.estimatesId = estimatesId;
	}

	@Column(name = "ESTIMATES_NAME", length = 50)
	public String getEstimatesName() {
		return this.estimatesName;
	}

	public void setEstimatesName(String estimatesName) {
		this.estimatesName = estimatesName;
	}

	@Column(name = "ESTIMATES_TYPE_CODE", length = 50)
	public String getEstimatesTypeCode() {
		return this.estimatesTypeCode;
	}

	public void setEstimatesTypeCode(String estimatesTypeCode) {
		this.estimatesTypeCode = estimatesTypeCode;
	}

	@Column(name = "ESTIMATES_TYPE_NAME", length = 50)
	public String getEstimatesTypeName() {
		return this.estimatesTypeName;
	}

	public void setEstimatesTypeName(String estimatesTypeName) {
		this.estimatesTypeName = estimatesTypeName;
	}

	@Column(name = "FINAL_BASE_AMOUNT", length = 50)
	public String getFinalBaseAmount() {
		return this.finalBaseAmount;
	}

	public void setFinalBaseAmount(String finalBaseAmount) {
		this.finalBaseAmount = finalBaseAmount;
	}

	@Column(name = "ORIGINAL_BASE_AMOUNT", length = 50)
	public String getOriginalBaseAmount() {
		return this.originalBaseAmount;
	}

	public void setOriginalBaseAmount(String originalBaseAmount) {
		this.originalBaseAmount = originalBaseAmount;
	}

	@Column(name = "APPROVED_CHANGE_AMOUNT", length = 50)
	public String getApprovedChangeAmount() {
		return this.approvedChangeAmount;
	}

	public void setApprovedChangeAmount(String approvedChangeAmount) {
		this.approvedChangeAmount = approvedChangeAmount;
	}

	@Column(name = "TODO_CHANGE_AMOUNT", length = 50)
	public String getTodoChangeAmount() {
		return this.todoChangeAmount;
	}

	public void setTodoChangeAmount(String todoChangeAmount) {
		this.todoChangeAmount = todoChangeAmount;
	}

	@Column(name = "SUPER_ESTIMATES_ID", length = 50)
	public String getSuperEstimatesId() {
		return this.superEstimatesId;
	}

	public void setSuperEstimatesId(String superEstimatesId) {
		this.superEstimatesId = superEstimatesId;
	}

	@Column(name = "LEVELS", length = 50)
	public String getLevels() {
		return this.levels;
	}

	public void setLevels(String levels) {
		this.levels = levels;
	}

	@Column(name = "CREATE_TIME", length = 50)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
