package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:24:44 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataSingle generated by hbm2java
 */
@Entity
@Table(name = "GREATA_SINGLE")
@XmlRootElement(name="SingleUnit")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataSingle implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 * 序号.
	 */
	private String id;
	/** */
	/**
	 * 单体代码.
	 */
	@XmlElement(name="SingleUnitCode")
	private String singleCode;
	/** */
	/**
	 * 单体类型.
	 */
	@XmlElement(name="SingleUnitType")
	private String singleType;
	/** */
	/**
	 * 单体名称.
	 */
	@XmlElement(name="SingleUnitName")
	private String singleName;
	/** */
	/**
	 * 所属线路.
	 */
	@XmlElement(name="Line")
	private String lineId;
	/** */
	/**
	 * 所属计划ID.
	 */
	@XmlElement(name="Plan")
	private String planId;
	/** */
	/**
	 * 删除位.
	 */
	private Integer removed = 0;
	/** */
	/**
	 * 创建时间.
	 */
	private String createTime = df.format(new Date());
	
	@XmlElement(name="SingleUnitID")
	private String singleId;

	public GreataSingle() {
	}

	public GreataSingle(String id) {
		this.id = id;
	}

	public GreataSingle(String id, String singleCode, String singleType,
			String singleName, String lineId, String planId, Integer removed,
			String createTime,String singleId) {
		this.id = id;
		this.singleCode = singleCode;
		this.singleType = singleType;
		this.singleName = singleName;
		this.lineId = lineId;
		this.planId = planId;
		this.removed = removed;
		this.createTime = createTime;
		this.singleId = singleId;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "SINGLE_CODE", length = 200)
	public String getSingleCode() {
		return this.singleCode;
	}

	public void setSingleCode(String singleCode) {
		this.singleCode = singleCode;
	}

	@Column(name = "SINGLE_TYPE", length = 200)
	public String getSingleType() {
		return this.singleType;
	}

	public void setSingleType(String singleType) {
		this.singleType = singleType;
	}

	@Column(name = "SINGLE_NAME", length = 200)
	public String getSingleName() {
		return this.singleName;
	}

	public void setSingleName(String singleName) {
		this.singleName = singleName;
	}

	@Column(name = "LINE_ID", length = 200)
	public String getLineId() {
		return this.lineId;
	}

	public void setLineId(String lineId) {
		this.lineId = lineId;
	}

	@Column(name = "PLAN_ID", length = 50)
	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	@Column(name = "REMOVED", precision = 5, scale = 0)
	public Integer getRemoved() {
		return this.removed;
	}

	public void setRemoved(Integer removed) {
		this.removed = removed;
	}

	@Column(name = "CREATE_TIME", length = 100)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "SINGLE_ID", length = 50)
	public String getSingleId() {
		return singleId;
	}

	public void setSingleId(String singleId) {
		this.singleId = singleId;
	}

	
}
