package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:55:00 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataAssetExecute generated by hbm2java
 */
@Entity
@Table(name = "GREATA_ASSET_EXECUTE")
@XmlRootElement(name="MExecute")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataAssetExecute implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 */
	private String id;
	/** */
	/**
	 * 项目id.
	 */
	@XmlElement(name="ProjectID")
	private String projectId;
	/** */
	/**
	 * 资金主键id.
	 */
	@XmlElement(name="MAmountID")
	private String amountId;
	/** */
	/**
	 * 资金执行名称.
	 */
	@XmlElement(name="MExcuteName")
	private String executeName;
	/** */
	/**
	 * 资金类别编码.
	 */
	@XmlElement(name="MTypeCode")
	private String typeCode;
	/** */
	/**
	 * 资金类别名称.
	 */
	@XmlElement(name="MTypeName")
	private String typeName;
	/** */
	/**
	 * 已签合同（元）.
	 */
	@XmlElement(name="DoneContractAmount")
	private String doneContractAmount;
	/** */
	/**
	 * 已批准变更（元）.
	 */
	@XmlElement(name="ApprovedChangeAmount")
	private String approvedChangeAmount;
	/** */
	/**
	 * 待批准变更（元）.
	 */
	@XmlElement(name="ToDoChangeAmount")
	private String todoChangeAmount;
	/** */
	/**
	 * 累计支付（元）.
	 */
	@XmlElement(name="TotalPayment")
	private String totalPayment;
	/** */
	/**
	 * 本月拟支付（元）.
	 */
	@XmlElement(name="ThisMonthPayment")
	private String thisMonthPayment;
	/** */
	/**
	 * 上级主键id.
	 */
	@XmlElement(name="SuperID")
	private String superId;
	/** */
	/**
	 * 层级.
	 */
	@XmlElement(name="Level")
	private String levels;
	/** */
	/**
	 * 概算id.
	 */
	@XmlElement(name="EstimatesID")
	private String estimatesId;
	/** */
	/**
	 */
	private String createTime = df.format(new Date());

	public GreataAssetExecute() {
	}

	public GreataAssetExecute(String id) {
		this.id = id;
	}

	public GreataAssetExecute(String id, String projectId, String amountId,
			String executeName, String typeCode, String typeName,
			String doneContractAmount, String approvedChangeAmount,
			String todoChangeAmount, String totalPayment,
			String thisMonthPayment, String superId, String levels,
			String estimatesId, String createTime) {
		this.id = id;
		this.projectId = projectId;
		this.amountId = amountId;
		this.executeName = executeName;
		this.typeCode = typeCode;
		this.typeName = typeName;
		this.doneContractAmount = doneContractAmount;
		this.approvedChangeAmount = approvedChangeAmount;
		this.todoChangeAmount = todoChangeAmount;
		this.totalPayment = totalPayment;
		this.thisMonthPayment = thisMonthPayment;
		this.superId = superId;
		this.levels = levels;
		this.estimatesId = estimatesId;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PROJECT_ID", length = 50)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "AMOUNT_ID", length = 50)
	public String getAmountId() {
		return this.amountId;
	}

	public void setAmountId(String amountId) {
		this.amountId = amountId;
	}

	@Column(name = "EXECUTE_NAME", length = 200)
	public String getExecuteName() {
		return this.executeName;
	}

	public void setExecuteName(String executeName) {
		this.executeName = executeName;
	}

	@Column(name = "TYPE_CODE", length = 50)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "TYPE_NAME", length = 50)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "DONE_CONTRACT_AMOUNT", length = 50)
	public String getDoneContractAmount() {
		return this.doneContractAmount;
	}

	public void setDoneContractAmount(String doneContractAmount) {
		this.doneContractAmount = doneContractAmount;
	}

	@Column(name = "APPROVED_CHANGE_AMOUNT", length = 50)
	public String getApprovedChangeAmount() {
		return this.approvedChangeAmount;
	}

	public void setApprovedChangeAmount(String approvedChangeAmount) {
		this.approvedChangeAmount = approvedChangeAmount;
	}

	@Column(name = "TODO_CHANGE_AMOUNT", length = 50)
	public String getTodoChangeAmount() {
		return this.todoChangeAmount;
	}

	public void setTodoChangeAmount(String todoChangeAmount) {
		this.todoChangeAmount = todoChangeAmount;
	}

	@Column(name = "TOTAL_PAYMENT", length = 50)
	public String getTotalPayment() {
		return this.totalPayment;
	}

	public void setTotalPayment(String totalPayment) {
		this.totalPayment = totalPayment;
	}

	@Column(name = "THIS_MONTH_PAYMENT", length = 50)
	public String getThisMonthPayment() {
		return this.thisMonthPayment;
	}

	public void setThisMonthPayment(String thisMonthPayment) {
		this.thisMonthPayment = thisMonthPayment;
	}

	@Column(name = "SUPER_ID", length = 50)
	public String getSuperId() {
		return this.superId;
	}

	public void setSuperId(String superId) {
		this.superId = superId;
	}

	@Column(name = "LEVELS", length = 50)
	public String getLevels() {
		return this.levels;
	}

	public void setLevels(String levels) {
		this.levels = levels;
	}

	@Column(name = "ESTIMATES_ID", length = 50)
	public String getEstimatesId() {
		return this.estimatesId;
	}

	public void setEstimatesId(String estimatesId) {
		this.estimatesId = estimatesId;
	}

	@Column(name = "CREATE_TIME", length = 50)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
