package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:24:44 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataPlanType generated by hbm2java
 */
@Entity
@Table(name = "GREATA_PLAN_TYPE")
@XmlRootElement(name="PlanType")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataPlanType implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 * 主键.
	 */
	private String id;
	/** */
	/**
	 * 计划类型.
	 */
	@XmlElement(name="TypeCode")
	private String planTypeCode;
	/** */
	/**
	 * 计划名称.
	 */
	@XmlElement(name="TypeName")
	private String planTypeName;
	/** */
	/**
	 * 所属计划ID.
	 */
	@XmlElement(name="Plan")
	private String planId;
	/** */
	/**
	 * 删除位.
	 */
	private Integer removed = 0;
	/** */
	/**
	 * 序号.
	 */
	@XmlElement(name="TypeID")
	private String planTypeId;
	/** */
	/**
	 * 创建时间.
	 */
	private String createTime = df.format(new Date());

	public GreataPlanType() {
	}

	public GreataPlanType(String id, String planTypeId) {
		this.id = id;
		this.planTypeId = planTypeId;
	}

	public GreataPlanType(String id, String planTypeCode, String planTypeName,
			String planId, Integer removed, String planTypeId, String createTime) {
		this.id = id;
		this.planTypeCode = planTypeCode;
		this.planTypeName = planTypeName;
		this.planId = planId;
		this.removed = removed;
		this.planTypeId = planTypeId;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PLAN_TYPE_CODE", length = 200)
	public String getPlanTypeCode() {
		return this.planTypeCode;
	}

	public void setPlanTypeCode(String planTypeCode) {
		this.planTypeCode = planTypeCode;
	}

	@Column(name = "PLAN_TYPE_NAME", length = 200)
	public String getPlanTypeName() {
		return this.planTypeName;
	}

	public void setPlanTypeName(String planTypeName) {
		this.planTypeName = planTypeName;
	}

	@Column(name = "PLAN_ID", length = 50)
	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	@Column(name = "REMOVED", precision = 5, scale = 0)
	public Integer getRemoved() {
		return this.removed;
	}

	public void setRemoved(Integer removed) {
		this.removed = removed;
	}

	@Column(name = "PLAN_TYPE_ID", nullable = false, length = 50)
	public String getPlanTypeId() {
		return this.planTypeId;
	}

	public void setPlanTypeId(String planTypeId) {
		this.planTypeId = planTypeId;
	}

	@Column(name = "CREATE_TIME", length = 100)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
