package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:24:44 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataEstimatesCompose generated by hbm2java
 */
@Entity
@Table(name = "GREATA_ESTIMATES_COMPOSE")
@XmlRootElement(name="EElement")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataEstimatesCompose implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 */
	private String id;
	/** */
	/**
	 * 概算主键id.
	 */
	@XmlElement(name="EstimatesID")
	private String estimatesId;
	/** */
	/**
	 * 主键id.
	 */
	@XmlElement(name="ElementID")
	private String elementId;
	/** */
	/**
	 * 组成编码.
	 */
	@XmlElement(name="ElementCode")
	private String elementCode;
	/** */
	/**
	 * 组成名称.
	 */
	@XmlElement(name="ElementName")
	private String elementName;
	/** */
	/**
	 * 级别.
	 */
	@XmlElement(name="Level")
	private String levels;
	/** */
	/**
	 * 创建时间.
	 */
	private String createTime = df.format(new Date());

	public GreataEstimatesCompose() {
	}

	public GreataEstimatesCompose(String id) {
		this.id = id;
	}

	public GreataEstimatesCompose(String id, String estimatesId,
			String elementId, String elementCode, String elementName,
			String levels) {
		this.id = id;
		this.estimatesId = estimatesId;
		this.elementId = elementId;
		this.elementCode = elementCode;
		this.elementName = elementName;
		this.levels = levels;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ESTIMATES_ID", length = 50)
	public String getEstimatesId() {
		return this.estimatesId;
	}

	public void setEstimatesId(String estimatesId) {
		this.estimatesId = estimatesId;
	}

	@Column(name = "ELEMENT_ID", length = 50)
	public String getElementId() {
		return this.elementId;
	}

	public void setElementId(String elementId) {
		this.elementId = elementId;
	}

	@Column(name = "ELEMENT_CODE", length = 50)
	public String getElementCode() {
		return this.elementCode;
	}

	public void setElementCode(String elementCode) {
		this.elementCode = elementCode;
	}

	@Column(name = "ELEMENT_NAME", length = 50)
	public String getElementName() {
		return this.elementName;
	}

	public void setElementName(String elementName) {
		this.elementName = elementName;
	}

	@Column(name = "LEVELS", length = 50)
	public String getLevels() {
		return this.levels;
	}

	public void setLevels(String levels) {
		this.levels = levels;
	}

	@Column(name = "CREATE_TIME", length = 100)
	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
