package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:24:44 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataQuality generated by hbm2java
 */
@Entity
@Table(name = "GREATA_QUALITY")
@XmlRootElement(name="QualitySafety")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataQuality implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 */
	private String id;
	/** */
	/**
	 * 项目id.
	 */
	@XmlElement(name="ProjectID")
	private String projectId;
	/** */
	/**
	 * 状态.
	 */
	@XmlElement(name="Status")
	private String status;
	/** */
	/**
	 * 风险类型.
	 */
	@XmlElement(name="RiskType")
	private String riskType;
	/** */
	/**
	 * 风险内容.
	 */
	@XmlElement(name="RiskContent")
	private String riskContent;
	/** */
	/**
	 * 预防措施.
	 */
	@XmlElement(name="Precautions")
	private String precautions;
	/** */
	/**
	 * 提交时间.
	 */
	@XmlElement(name="SubmitTime")
	private String submitTime;
	/** */
	/**
	 * 提交人.
	 */
	@XmlElement(name="Submitter")
	private String submitter;
	/** */
	/**
	 */
	private String createTime = df.format(new Date());

	public GreataQuality() {
	}

	public GreataQuality(String id) {
		this.id = id;
	}

	public GreataQuality(String id, String projectId, String status,
			String riskType, String riskContent, String precautions,
			String submitTime, String submitter, String createTime) {
		this.id = id;
		this.projectId = projectId;
		this.status = status;
		this.riskType = riskType;
		this.riskContent = riskContent;
		this.precautions = precautions;
		this.submitTime = submitTime;
		this.submitter = submitter;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PROJECT_ID", length = 50)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "RISK_TYPE", length = 50)
	public String getRiskType() {
		return this.riskType;
	}

	public void setRiskType(String riskType) {
		this.riskType = riskType;
	}

	@Column(name = "RISK_CONTENT", length = 4000)
	public String getRiskContent() {
		return this.riskContent;
	}

	public void setRiskContent(String riskContent) {
		this.riskContent = riskContent;
	}

	@Column(name = "PRECAUTIONS", length = 4000)
	public String getPrecautions() {
		return this.precautions;
	}

	public void setPrecautions(String precautions) {
		this.precautions = precautions;
	}

	@Column(name = "SUBMIT_TIME", length = 50)
	public String getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(String submitTime) {
		this.submitTime = submitTime;
	}

	@Column(name = "SUBMITTER", length = 50)
	public String getSubmitter() {
		return this.submitter;
	}

	public void setSubmitter(String submitter) {
		this.submitter = submitter;
	}

	@Column(name = "CREATE_TIME", length = 50)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
