package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:24:44 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataPlanTask generated by hbm2java
 */
@Entity
@Table(name = "GREATA_PLAN_TASK")
@XmlRootElement(name="ProecssPlanTask")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataPlanTask implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 * 主键.
	 */
	private String id;
	/** */
	/**
	 * 序号.
	 */
	@XmlElement(name="PlanID")
	private String planId;
	/** */
	/**
	 * 计划编号.
	 */
	@XmlElement(name="PlanNo")
	private String planNum;
	/** */
	/**
	 * 计划名称.
	 */
	@XmlElement(name="PlanName")
	private String planName;
	/** */
	/**
	 * 相关项目ID 关联表 T_BULID_PROJECT.
	 */
	@XmlElement(name="Project")
	private String projectId;
	/** */
	/**
	 * 当前版本.
	 */
	@XmlElement(name="CurrVersion")
	private String curVersion;
	/** */
	/**
	 * 版本日期.
	 */
	@XmlElement(name="VersionDate")
	private String versionDate;
	/** */
	/**
	 * 是否里程碑 0 否 1 是.
	 */
	@XmlElement(name="Is_Milestone")
	private String milestone;
	/** */
	/**
	 * 父计划ID.
	 */
	@XmlElement(name="SuperPlanTask")
	private String parentPlanId;
	/** */
	/**
	 * 层级.
	 */
	@XmlElement(name="PlanLayer")
	private String planLevel;
	/** */
	/**
	 * 负责人.
	 */
	@XmlElement(name="PersonInCharge")
	private String chargePerson;
	/** */
	/**
	 * 计量单位.
	 */
	@XmlElement(name="Unit")
	private String unit;
	/** */
	/**
	 * 计划开始时间.
	 */
	@XmlElement(name="PlanStartDate")
	private String planBeginTime;
	/** */
	/**
	 * 计划完成时间.
	 */
	@XmlElement(name="PlanEndDate")
	private String planFinishTime;
	/** */
	/**
	 * 计划工期.
	 */
	@XmlElement(name="PlanDuration")
	private String planDuration;
	/** */
	/**
	 * 计划完成量.
	 */
	@XmlElement(name="PlanDoneLoad")
	private String planCompletion;
	/** */
	/**
	 * 实际开始时间.
	 */
	@XmlElement(name="ActualStartDate")
	private String realBeginTime;
	/** */
	/**
	 * 实际完成时间.
	 */
	@XmlElement(name="ActualEndDate")
	private String realFinishTime;
	/** */
	/**
	 * 实际工期.
	 */
	@XmlElement(name="ActualDuration")
	private String realDuration;
	/** */
	/**
	 * 本月完成量.
	 */
	@XmlElement(name="CurrMonthDoneLoad")
	private String curMonthCompletion;
	/** */
	/**
	 * 本月计划量.
	 */
	@XmlElement(name="ThisMonthPlan")
	private String curMonthPlanCompletion;
	/** */
	/**
	 * 本月完成比.
	 */
	@XmlElement(name="ThisMonthDonePercent")
	private String curMonthCompletionPercent;
	/** */
	/**
	 * 下月计划量.
	 */
	@XmlElement(name="NextMonthPlan")
	private String nextMonthPlanCompletion;
	/** */
	/**
	 * 累计完成量.
	 */
	@XmlElement(name="TotalDoneLoad")
	private String totalCompletion;
	/** */
	/**
	 * 累计完成百分比.
	 */
	@XmlElement(name="ActualDonePercent")
	private String totalCompletionPercent;
	/** */
	/**
	 * 最后更新时间.
	 */
	@XmlElement(name="LastUpdateDate")
	private String operateTime;
	/** */
	/**
	 * 删除位.
	 */
	private Integer removed = 0;
	/** */
	/**
	 * 创建时间.
	 */
	private String createTime = df.format(new Date());
	
	@XmlElement(name="PlanTaskType")
	private String planType;

	public GreataPlanTask() {
		
	}

	public GreataPlanTask(String id, String planId) {
		this.id = id;
		this.planId = planId;
	}

	public GreataPlanTask(String id, String planId, String planNum,
			String planName, String projectId, String curVersion,
			String versionDate, String milestone, 
			String parentPlanId, String planLevel, String chargePerson,
			String unit, String planBeginTime, String planFinishTime,
			String planDuration, String planCompletion, String realBeginTime,
			String realFinishTime, String realDuration,
			String curMonthCompletion, String curMonthPlanCompletion,
			String curMonthCompletionPercent, String nextMonthPlanCompletion,
			String totalCompletion, String totalCompletionPercent,
			String operateTime, Integer removed, String createTime) {
		this.id = id;
		this.planId = planId;
		this.planNum = planNum;
		this.planName = planName;
		this.projectId = projectId;
		this.curVersion = curVersion;
		this.versionDate = versionDate;
		this.milestone = milestone;
		this.parentPlanId = parentPlanId;
		this.planLevel = planLevel;
		this.chargePerson = chargePerson;
		this.unit = unit;
		this.planBeginTime = planBeginTime;
		this.planFinishTime = planFinishTime;
		this.planDuration = planDuration;
		this.planCompletion = planCompletion;
		this.realBeginTime = realBeginTime;
		this.realFinishTime = realFinishTime;
		this.realDuration = realDuration;
		this.curMonthCompletion = curMonthCompletion;
		this.curMonthPlanCompletion = curMonthPlanCompletion;
		this.curMonthCompletionPercent = curMonthCompletionPercent;
		this.nextMonthPlanCompletion = nextMonthPlanCompletion;
		this.totalCompletion = totalCompletion;
		this.totalCompletionPercent = totalCompletionPercent;
		this.operateTime = operateTime;
		this.removed = removed;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PLAN_ID", nullable = false, length = 50)
	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	@Column(name = "PLAN_NUM", length = 100)
	public String getPlanNum() {
		return this.planNum;
	}

	public void setPlanNum(String planNum) {
		this.planNum = planNum;
	}

	@Column(name = "PLAN_NAME", length = 200)
	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	@Column(name = "PROJECT_ID", length = 50)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "CUR_VERSION", length = 50)
	public String getCurVersion() {
		return this.curVersion;
	}

	public void setCurVersion(String curVersion) {
		this.curVersion = curVersion;
	}

	@Column(name = "VERSION_DATE", length = 20)
	public String getVersionDate() {
		return this.versionDate;
	}

	public void setVersionDate(String versionDate) {
		this.versionDate = versionDate;
	}

	@Column(name = "MILESTONE", length = 1)
	public String getMilestone() {
		return this.milestone;
	}

	public void setMilestone(String milestone) {
		this.milestone = milestone;
	}


	@Column(name = "PARENT_PLAN_ID", length = 50)
	public String getParentPlanId() {
		return this.parentPlanId;
	}

	public void setParentPlanId(String parentPlanId) {
		this.parentPlanId = parentPlanId;
	}

	@Column(name = "PLAN_LEVEL", length = 10)
	public String getPlanLevel() {
		return this.planLevel;
	}

	public void setPlanLevel(String planLevel) {
		this.planLevel = planLevel;
	}

	@Column(name = "CHARGE_PERSON", length = 50)
	public String getChargePerson() {
		return this.chargePerson;
	}

	public void setChargePerson(String chargePerson) {
		this.chargePerson = chargePerson;
	}

	@Column(name = "UNIT", length = 20)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "PLAN_BEGIN_TIME", length = 20)
	public String getPlanBeginTime() {
		return this.planBeginTime;
	}

	public void setPlanBeginTime(String planBeginTime) {
		this.planBeginTime = planBeginTime;
	}

	@Column(name = "PLAN_FINISH_TIME", length = 20)
	public String getPlanFinishTime() {
		return this.planFinishTime;
	}

	public void setPlanFinishTime(String planFinishTime) {
		this.planFinishTime = planFinishTime;
	}

	@Column(name = "PLAN_DURATION", length = 20)
	public String getPlanDuration() {
		return this.planDuration;
	}

	public void setPlanDuration(String planDuration) {
		this.planDuration = planDuration;
	}

	@Column(name = "PLAN_COMPLETION", length = 20)
	public String getPlanCompletion() {
		return this.planCompletion;
	}

	public void setPlanCompletion(String planCompletion) {
		this.planCompletion = planCompletion;
	}

	@Column(name = "REAL_BEGIN_TIME", length = 20)
	public String getRealBeginTime() {
		return this.realBeginTime;
	}

	public void setRealBeginTime(String realBeginTime) {
		this.realBeginTime = realBeginTime;
	}

	@Column(name = "REAL_FINISH_TIME", length = 20)
	public String getRealFinishTime() {
		return this.realFinishTime;
	}

	public void setRealFinishTime(String realFinishTime) {
		this.realFinishTime = realFinishTime;
	}

	@Column(name = "REAL_DURATION", length = 20)
	public String getRealDuration() {
		return this.realDuration;
	}

	public void setRealDuration(String realDuration) {
		this.realDuration = realDuration;
	}

	@Column(name = "CUR_MONTH_COMPLETION", length = 20)
	public String getCurMonthCompletion() {
		return this.curMonthCompletion;
	}

	public void setCurMonthCompletion(String curMonthCompletion) {
		this.curMonthCompletion = curMonthCompletion;
	}

	@Column(name = "CUR_MONTH_PLAN_COMPLETION", length = 20)
	public String getCurMonthPlanCompletion() {
		return this.curMonthPlanCompletion;
	}

	public void setCurMonthPlanCompletion(String curMonthPlanCompletion) {
		this.curMonthPlanCompletion = curMonthPlanCompletion;
	}

	@Column(name = "CUR_MONTH_COMPLETION_PERCENT", length = 20)
	public String getCurMonthCompletionPercent() {
		return this.curMonthCompletionPercent;
	}

	public void setCurMonthCompletionPercent(String curMonthCompletionPercent) {
		this.curMonthCompletionPercent = curMonthCompletionPercent;
	}

	@Column(name = "NEXT_MONTH_PLAN_COMPLETION", length = 20)
	public String getNextMonthPlanCompletion() {
		return this.nextMonthPlanCompletion;
	}

	public void setNextMonthPlanCompletion(String nextMonthPlanCompletion) {
		this.nextMonthPlanCompletion = nextMonthPlanCompletion;
	}

	@Column(name = "TOTAL_COMPLETION", length = 20)
	public String getTotalCompletion() {
		return this.totalCompletion;
	}

	public void setTotalCompletion(String totalCompletion) {
		this.totalCompletion = totalCompletion;
	}

	@Column(name = "TOTAL_COMPLETION_PERCENT", length = 20)
	public String getTotalCompletionPercent() {
		return this.totalCompletionPercent;
	}

	public void setTotalCompletionPercent(String totalCompletionPercent) {
		this.totalCompletionPercent = totalCompletionPercent;
	}

	@Column(name = "OPERATE_TIME", length = 20)
	public String getOperateTime() {
		return this.operateTime;
	}

	public void setOperateTime(String operateTime) {
		this.operateTime = operateTime;
	}

	@Column(name = "REMOVED", precision = 5, scale = 0)
	public Integer getRemoved() {
		return this.removed;
	}

	public void setRemoved(Integer removed) {
		this.removed = removed;
	}

	@Column(name = "CREATE_TIME", length = 100)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "PLAN_TYPE", length = 100)
	public String getPlanType() {
		return planType;
	}

	public void setPlanType(String planType) {
		this.planType = planType;
	}

	
}
