package com.wonders.stpt.ThemeDatabase.model.bo;

// Generated 2013-11-26 13:24:44 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * GreataProject generated by hbm2java
 */
@Entity
@Table(name = "GREATA_PROJECT")
@XmlRootElement(name="ProjectData")
@XmlAccessorType(XmlAccessType.NONE)
public class GreataProject implements java.io.Serializable {
	private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
	/** */
	/**
	 * 主键.
	 */
	private String id;
	/** */
	/**
	 * 序号.
	 */
	@XmlElement(name="ProjectID")
	private String projectId;
	/** */
	/**
	 * 协同平台项目ID.
	 */
	@XmlElement(name="PlatformID")
	private String oaId;
	/** */
	/**
	 * 项目编号.
	 */
	@XmlElement(name="ProjectNo")
	private String projectNum;
	/** */
	/**
	 * 项目名称.
	 */
	@XmlElement(name="ProjectName")
	private String projectName;
	/** */
	/**
	 * 项目简称.
	 */
	@XmlElement(name="ProjectShortName")
	private String projectShortName;
	/** */
	/**
	 * 项目简介.
	 */
	@XmlElement(name="ProjectBrief")
	private String projectProfile;
	/** */
	/**
	 * 项目造价.
	 */
	@XmlElement(name="ProjectCost")
	private String projectCost;
	/** */
	/**
	 * 项目状态，1为待建，2为在建，3为竣工.
	 */
	@XmlElement(name="ProjectStatus")
	private String projectStatus;
	/** */
	/**
	 * 计划开始日期.
	 */
	@XmlElement(name="StartTime")
	private String planBeginTime;
	/** */
	/**
	 * 计划完成日期.
	 */
	@XmlElement(name="EndTime")
	private String planFinishTime;
	/** */
	/**
	 * 实际开始日期.
	 */
	@XmlElement(name="ActualStartDate")
	private String realBeginTime;
	/** */
	/**
	 * 实际竣工时间.
	 */
	@XmlElement(name="ActualEndDate")
	private String realFinishTime;
	/** */
	/**
	 * 项目公司ID.
	 */
	@XmlElement(name="ProjectCorpID")
	private String projectCompanyId;
	/** */
	/**
	 * 所属线路ID.
	 */
	@XmlElement(name="LineID")
	private String lineId;
	/** */
	/**
	 * 删除位.
	 */
	private Integer removed = 0;
	/** */
	/**
	 * 创建时间.
	 */
	private String createTime = df.format(new Date());

	public GreataProject() {
	}

	public GreataProject(String id, String projectId) {
		this.id = id;
		this.projectId = projectId;
	}

	public GreataProject(String id, String projectId, String oaId,
			String projectNum, String projectName, String projectShortName,
			String projectProfile, String projectCost, String projectStatus,
			String planBeginTime, String planFinishTime, String realBeginTime,
			String realFinishTime, String projectCompanyId, String lineId,
			Integer removed, String createTime) {
		this.id = id;
		this.projectId = projectId;
		this.oaId = oaId;
		this.projectNum = projectNum;
		this.projectName = projectName;
		this.projectShortName = projectShortName;
		this.projectProfile = projectProfile;
		this.projectCost = projectCost;
		this.projectStatus = projectStatus;
		this.planBeginTime = planBeginTime;
		this.planFinishTime = planFinishTime;
		this.realBeginTime = realBeginTime;
		this.realFinishTime = realFinishTime;
		this.projectCompanyId = projectCompanyId;
		this.lineId = lineId;
		this.removed = removed;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "PROJECT_ID", nullable = false, length = 50)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "OA_ID", length = 50)
	public String getOaId() {
		return this.oaId;
	}

	public void setOaId(String oaId) {
		this.oaId = oaId;
	}

	@Column(name = "PROJECT_NUM", length = 100)
	public String getProjectNum() {
		return this.projectNum;
	}

	public void setProjectNum(String projectNum) {
		this.projectNum = projectNum;
	}

	@Column(name = "PROJECT_NAME", length = 200)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "PROJECT_SHORT_NAME", length = 200)
	public String getProjectShortName() {
		return this.projectShortName;
	}

	public void setProjectShortName(String projectShortName) {
		this.projectShortName = projectShortName;
	}

	@Column(name = "PROJECT_PROFILE", length = 2000)
	public String getProjectProfile() {
		return this.projectProfile;
	}

	public void setProjectProfile(String projectProfile) {
		this.projectProfile = projectProfile;
	}

	@Column(name = "PROJECT_COST", length = 50)
	public String getProjectCost() {
		return this.projectCost;
	}

	public void setProjectCost(String projectCost) {
		this.projectCost = projectCost;
	}

	@Column(name = "PROJECT_STATUS", length = 1)
	public String getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	@Column(name = "PLAN_BEGIN_TIME", length = 20)
	public String getPlanBeginTime() {
		return this.planBeginTime;
	}

	public void setPlanBeginTime(String planBeginTime) {
		this.planBeginTime = planBeginTime;
	}

	@Column(name = "PLAN_FINISH_TIME", length = 20)
	public String getPlanFinishTime() {
		return this.planFinishTime;
	}

	public void setPlanFinishTime(String planFinishTime) {
		this.planFinishTime = planFinishTime;
	}

	@Column(name = "REAL_BEGIN_TIME", length = 20)
	public String getRealBeginTime() {
		return this.realBeginTime;
	}

	public void setRealBeginTime(String realBeginTime) {
		this.realBeginTime = realBeginTime;
	}

	@Column(name = "REAL_FINISH_TIME", length = 20)
	public String getRealFinishTime() {
		return this.realFinishTime;
	}

	public void setRealFinishTime(String realFinishTime) {
		this.realFinishTime = realFinishTime;
	}

	@Column(name = "PROJECT_COMPANY_ID", length = 50)
	public String getProjectCompanyId() {
		return this.projectCompanyId;
	}

	public void setProjectCompanyId(String projectCompanyId) {
		this.projectCompanyId = projectCompanyId;
	}

	@Column(name = "LINE_ID", length = 50)
	public String getLineId() {
		return this.lineId;
	}

	public void setLineId(String lineId) {
		this.lineId = lineId;
	}

	@Column(name = "REMOVED", precision = 5, scale = 0)
	public Integer getRemoved() {
		return this.removed;
	}

	public void setRemoved(Integer removed) {
		this.removed = removed;
	}

	@Column(name = "CREATE_TIME", length = 100)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

}
