
CREATE TABLE T_PROCESS_DONE
(
  ID       					VARCHAR2(50)                  DEFAULT SYS_GUID()            NOT NULL,
  PID      					VARCHAR2(50),
  PNAME 		 				VARCHAR2(50),
  PTYPE      				VARCHAR2(50),  
  SUMMARY  					VARCHAR2(2000),  
  START_TIME  				DATE,
  END_TIME  					DATE,
  APPLY_USER     		VARCHAR2(25),  
  APPLY_DEPT        VARCHAR2(50),  
  DONE_USERS      	VARCHAR2(500),
  STATUS            INTEGER                             DEFAULT 0,
  DATA           		CLOB  ,
  REMARK				VARCHAR2(200),
  CONSTRAINT PK_T_PROCESS_DONE PRIMARY KEY (ID)
);


COMMENT ON TABLE T_PROCESS_DONE IS '已办流程信息表';

COMMENT ON COLUMN T_PROCESS_DONE.ID IS '系统主键';

COMMENT ON COLUMN T_PROCESS_DONE.PID IS '流程ID';

COMMENT ON COLUMN T_PROCESS_DONE.PNAME IS '流程名称，中文标识';

COMMENT ON COLUMN T_PROCESS_DONE.PTYPE IS '流程类型,英文标识';

COMMENT ON COLUMN T_PROCESS_DONE.SUMMARY IS '摘要';

COMMENT ON COLUMN T_PROCESS_DONE.START_TIME IS '开始时间';

COMMENT ON COLUMN T_PROCESS_DONE.END_TIME IS '完成时间';

COMMENT ON COLUMN T_PROCESS_DONE.APPLY_USER IS '发起人姓名';

COMMENT ON COLUMN T_PROCESS_DONE.APPLY_DEPT IS '发起部门名称';

COMMENT ON COLUMN T_PROCESS_DONE.DONE_USERS IS '已办理人工号,以逗号分隔的多个用户工号（16位带部门ID）';

COMMENT ON COLUMN T_PROCESS_DONE.STATUS IS '完成状态（0:进行中，1：已完成）';

COMMENT ON COLUMN T_PROCESS_DONE.DATA IS '业务数据';

COMMENT ON COLUMN T_PROCESS_DONE.REMARK IS '备注';

CREATE INDEX IDX_T_PROCESS_DONE_PID_PNAME ON T_PROCESS_DONE
(PID,PNAME);

CREATE INDEX IDX_T_PROCESS_DONE_PTYPE ON T_PROCESS_DONE
(PTYPE);

alter table T_PROCESS_DONE add TASKID VARCHAR2(64);
COMMENT ON COLUMN T_PROCESS_DONE.TASKID IS 'tasks表主键';

update t_process_done t set t.taskid = (select a.taskid from tasks_bak a where a.steplabel='Begin' and a.incident=t.pid and a.processName=t.pname)




